/**
 * The /proposal deck: a visual walkthrough of the M&P Flow demo.
 *
 * The reader has no time to click through the live demo, so the deck *is* the
 * tour. Every slide is a headline, ONE big picture or diagram, and at most
 * three short numbered captions. No paragraphs.
 *
 * Every string the deck renders lives in this file — captions, diagram labels,
 * alt text, button labels — so copy is edited in one place and one lint can
 * police all of it. `scripts/check-proposal-copy.mjs` imports this module and
 * enforces:
 *
 *   - the banned vocabulary (never name the customer's current software, and
 *     never use engineering words: API, webhook, integration, sync, database…),
 *   - headline at most 10 words,
 *   - each caption at most 25 words,
 *   - at most 3 captions per slide,
 *   - under 60 words of body text per slide (everything but kicker and
 *     headline; alt text is scanned for banned words but not counted).
 *
 * Screenshots under /proposal/*.png come from the demo itself and are
 * regenerated by `node scripts/capture-proposal-shots.mjs`.
 */

/** A numbered badge drawn over a screenshot, positioned in percent of the picture box. */
export interface Mark {
  n: number
  /** 0–100, from the left edge of the picture. */
  x: number
  /** 0–100, from the top edge of the picture. */
  y: number
}

/** A numbered caption. `n` matches the badge on the picture when there is one. */
export interface Caption {
  n: number
  text: string
}

/** One step in the five-step trial strip. */
export interface StripStep {
  label: string
}

export type SlideVisual =
  /** A screenshot of the running demo, with numbered badges over it. */
  | { kind: 'shot'; src: string; alt: string; marks?: readonly Mark[] }
  /** Today: one shipment, seen in pieces across three places. */
  | {
      kind: 'diagram'
      name: 'today'
      alt: string
      channels: readonly { label: string; line: string }[]
      centre: string
    }
  /** The trial beside the system they use today. */
  | {
      kind: 'diagram'
      name: 'two-systems'
      alt: string
      here: string
      hereSub: string
      there: string
      thereSub: string
      arrow: string
    }
  /** The discovery session and the three paths a fact can take. */
  | { kind: 'diagram'; name: 'discovery'; alt: string; source: string; options: readonly string[] }
  /** The trial drawn as a strip of numbered steps. */
  | { kind: 'strip'; steps: readonly StripStep[] }
  /** The four asks, drawn as numbered cards. */
  | { kind: 'asks'; items: readonly string[] }
  /** A big link out to the live demo. */
  | { kind: 'link'; href: string; label: string; note: string }
  /** Title slide: the headline carries it. */
  | { kind: 'none' }

export interface Slide {
  /** URL slug: /proposal?slide=<id>. Stable when slides are reordered. */
  id: string
  /** Small label above the headline, e.g. "Your concern". */
  kicker?: string
  /** At most ten words. */
  title: string
  /** One short line under the headline. */
  lead?: string
  visual: SlideVisual
  /** At most three, each at most 25 words. */
  captions?: readonly Caption[]
  /** A small line at the foot of the slide. */
  note?: string
  /** Charcoal background with white text. Only the title slide uses it. */
  tone?: 'dark' | 'light'
}

export const PROPOSAL_SLIDES: readonly Slide[] = [
  {
    id: 'title',
    kicker: 'A walk through the demo',
    title: 'M&P Flow: what the demo shows',
    lead: 'A short trial with a few customers first.',
    tone: 'dark',
    visual: { kind: 'none' },
    note: 'Every picture in here is from a demo with made-up customers and made-up shipments.'
  },
  {
    id: 'today',
    kicker: 'Today',
    title: 'One shipment, three separate places',
    visual: {
      kind: 'diagram',
      name: 'today',
      alt: 'WhatsApp, email and paper notes above one shipment bar broken into three pieces.',
      channels: [
        { label: 'WhatsApp', line: '“Where is my cargo?”' },
        { label: 'Email', line: 'Packing list attached' },
        { label: 'Paper notes', line: 'CFS waiting' }
      ],
      centre: 'One shipment, seen in pieces'
    },
    captions: [
      { n: 1, text: 'Each place holds part of the job, and none of them holds all of it.' },
      { n: 2, text: 'Answering a customer means remembering which place to look in.' },
      { n: 3, text: 'On a busy day, a message or a review slips past.' }
    ]
  },
  {
    id: 'doors',
    kicker: 'The demo',
    title: 'Three doors: ops, client, driver',
    visual: {
      kind: 'shot',
      src: '/proposal/doors.png',
      alt: 'The demo front page with three buttons: Internal ops, Client portal and Driver.',
      marks: [
        { n: 1, x: 23, y: 45 },
        { n: 2, x: 50, y: 45 },
        { n: 3, x: 77, y: 45 }
      ]
    },
    captions: [
      { n: 1, text: 'Internal ops: your team’s screens — jobs, messages, customs, reviews.' },
      { n: 2, text: 'Client portal: what your customer sees about their own shipments.' },
      { n: 3, text: 'Driver: today’s jobs on a phone, photos and status.' }
    ]
  },
  {
    id: 'jobs',
    kicker: 'Jobs',
    title: 'Every shipment is one job',
    visual: {
      kind: 'shot',
      src: '/proposal/jobs.png',
      alt: 'The jobs list, with a strip of counters above one row per shipment.',
      marks: [
        { n: 1, x: 50, y: 14 },
        { n: 2, x: 45, y: 48 },
        { n: 3, x: 23, y: 59 }
      ]
    },
    captions: [
      { n: 1, text: 'The strip at the top counts what needs a person right now.' },
      { n: 2, text: 'One row per shipment: client, mode, status, what is missing.' },
      { n: 3, text: 'Open a row to see the whole job.' }
    ]
  },
  {
    id: 'job-card',
    kicker: 'Jobs',
    title: 'The job card holds the whole story',
    visual: {
      kind: 'shot',
      src: '/proposal/job-card.png',
      alt: 'One job card: status and timeline, the documents checklist, partners and messages.',
      marks: [
        { n: 1, x: 45, y: 57 },
        { n: 2, x: 85, y: 20 },
        { n: 3, x: 85, y: 76 }
      ]
    },
    captions: [
      { n: 1, text: 'Status and timeline: what has happened, and what happens next.' },
      { n: 2, text: 'Documents received and still missing, named one by one.' },
      { n: 3, text: 'The claim and the review ask sit on the same card.' }
    ]
  },
  {
    id: 'messages',
    kicker: 'Messages',
    title: 'WhatsApp and email under the job',
    visual: {
      kind: 'shot',
      src: '/proposal/inbox.png',
      alt: 'One list of threads, WhatsApp and email together, each already on its job.',
      marks: [
        { n: 1, x: 30, y: 28 },
        { n: 2, x: 30, y: 38 },
        { n: 3, x: 60, y: 88 }
      ]
    },
    captions: [
      { n: 1, text: 'One list, both channels, each message already sitting on its job.' },
      { n: 2, text: 'Brendan’s WhatsApp on MP-3318-MC is still waiting on a reply.' },
      { n: 3, text: 'Staff reply from here, and the reply is filed on the job.' }
    ]
  },
  {
    id: 'reviews',
    kicker: 'Reviews',
    title: 'Reviews: asked, received, held',
    visual: {
      kind: 'shot',
      src: '/proposal/reviews.png',
      alt: 'The reviews board in three columns: asked, received and held.',
      marks: [
        { n: 1, x: 38, y: 25 },
        { n: 2, x: 45, y: 42 },
        { n: 3, x: 88, y: 48 }
      ]
    },
    captions: [
      { n: 1, text: 'Nobody asks the wrong customer at the wrong moment.' },
      { n: 2, text: 'After a clean job, the customer is asked for a review.' },
      { n: 3, text: 'MP-8125-HF is held because a damage claim is open.' }
    ]
  },
  {
    id: 'rewards',
    kicker: 'Rewards',
    title: 'A small thank-you for a good review',
    visual: {
      kind: 'shot',
      src: '/proposal/rewards.png',
      alt: 'The review programme board showing rewards issued against reviewed jobs.',
      marks: [
        { n: 1, x: 41, y: 34 },
        { n: 2, x: 88, y: 14 },
        { n: 3, x: 63, y: 47 }
      ]
    },
    captions: [
      { n: 1, text: 'A good review can earn the customer a small voucher.' },
      { n: 2, text: 'Staff see how many vouchers went out, and to whom.' },
      { n: 3, text: 'Each programme shows asks sent, reviews back, and what it cost.' }
    ]
  },
  {
    id: 'two-systems',
    kicker: 'Your concern',
    title: 'Your concern: typing into two systems',
    visual: {
      kind: 'diagram',
      name: 'two-systems',
      alt: 'A small trial box beside the system you use today, with one arrow between them.',
      here: 'M&P Flow',
      hereSub: 'a few trial customers',
      there: 'The system you use today',
      thereSub: 'everyone else, unchanged',
      arrow: 'copied across daily, once we have looked at your system'
    },
    captions: [
      { n: 1, text: 'The trial team works in M&P Flow for those few customers.' },
      { n: 2, text: 'Their records still show up where your colleagues already look.' },
      { n: 3, text: 'Nobody outside the trial changes anything.' }
    ]
  },
  {
    id: 'trial',
    kicker: 'The trial',
    title: 'How the trial works, in five steps',
    visual: {
      kind: 'strip',
      steps: [
        { label: 'Pick a few customers' },
        { label: 'Trial team works in M&P Flow' },
        { label: 'Their records stay visible in your system' },
        { label: 'A daily copy across, once we have looked' },
        { label: 'Everyone else carries on as now' }
      ]
    },
    captions: [{ n: 1, text: 'Stop after a few weeks if it has not earned its place.' }]
  },
  {
    id: 'before-daily-copy',
    kicker: 'Before we promise',
    title: 'Before we promise a daily copy',
    visual: {
      kind: 'diagram',
      name: 'discovery',
      alt: 'One session at the top, three paths below it for what each fact can do.',
      source: 'One short session with the person who uses it most',
      options: ['Connect directly', 'Send an official file daily', 'Keep as a checklist for now']
    },
    captions: [
      { n: 1, text: 'We have not seen your system yet, so we promise nothing about it.' },
      { n: 2, text: 'Each fact takes one of the three paths.' },
      { n: 3, text: 'Anything uncertain stays with a person until we are sure.' }
    ]
  },
  {
    id: 'live-demo',
    kicker: 'Optional',
    title: 'Try it yourself, if you have ten minutes',
    visual: {
      kind: 'link',
      href: 'https://mnp-flow.vercel.app',
      label: 'mnp-flow.vercel.app',
      note: 'Made-up customers. You cannot break it.'
    },
    captions: [
      { n: 1, text: 'Open Internal ops, then Jobs, and look for MP-3318-MC.' },
      { n: 2, text: 'Open Inbox and look for Brendan’s WhatsApp waiting on a reply.' },
      { n: 3, text: 'Open Reviews and look for the ask held by a claim.' }
    ]
  },
  {
    id: 'asking',
    kicker: 'Next steps',
    title: 'What we are asking',
    visual: {
      kind: 'asks',
      items: [
        'Agree a short list of trial customers.',
        'Agree which facts must stay visible in your system.',
        'Book one session to look at that system.',
        'Start the trial once that list is clear.'
      ]
    },
    note: 'Thank you for the time you have given us.'
  }
]

export function slideIndexById(id: unknown): number {
  const i = PROPOSAL_SLIDES.findIndex((s) => s.id === id)
  return i === -1 ? 0 : i
}

/**
 * Every string a slide renders on screen, minus the kicker and headline.
 * Alt text is excluded: it is scanned for banned words separately, but it is
 * not body copy and does not count against the 60-word budget.
 */
export function slideBodyStrings(slide: Slide): string[] {
  const out: string[] = []
  if (slide.lead) out.push(slide.lead)

  const v = slide.visual
  if (v.kind === 'diagram' && v.name === 'today') {
    for (const c of v.channels) out.push(c.label, c.line)
    out.push(v.centre)
  } else if (v.kind === 'diagram' && v.name === 'two-systems') {
    out.push(v.here, v.hereSub, v.there, v.thereSub, v.arrow)
  } else if (v.kind === 'diagram' && v.name === 'discovery') {
    out.push(v.source, ...v.options)
  } else if (v.kind === 'strip') {
    out.push(...v.steps.map((s) => s.label))
  } else if (v.kind === 'asks') {
    out.push(...v.items)
  } else if (v.kind === 'link') {
    out.push(v.label, v.note)
  }

  for (const c of slide.captions ?? []) out.push(c.text)
  if (slide.note) out.push(slide.note)
  return out
}

/** Alt text on a slide's picture or diagram — scanned for banned words, never counted. */
export function slideAltStrings(slide: Slide): string[] {
  return slide.visual.kind === 'shot' || slide.visual.kind === 'diagram' ? [slide.visual.alt] : []
}

/** Words in a piece of copy. */
export function countWords(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length
}

/** Body words on a slide: the 60-word budget the deck is written to. */
export function slideBodyWords(slide: Slide): number {
  return slideBodyStrings(slide).reduce((n, s) => n + countWords(s), 0)
}
